spring:
  main:
    banner-mode: off
  kafka:
    consumer:
      group-id: vc-server-it
      auto-offset-reset: latest
    producer:
      acks: all

# Integration test Kafka configuration (uses Testcontainers single broker)
kafka:
  # Testcontainers uses single broker (RF=1 is correct)
  partitions: 3
  replication-factor: 1

  # Disable transactions (simplifies test setup)
  transactional-id-prefix: ""

  # Producer: Fast for tests
  producer:
    acks: 1
    enable-idempotence: false
    compression-type: none
    retries: 3

  # Consumer: Fast for tests
  consumer:
    isolation-level: read_uncommitted
    enable-auto-commit: true
    auto-commit-interval-ms: 100  # Faster commits for tests
    max-poll-records: 500

# Disable ReadModelProjector in integration tests for test isolation
projector:
  kafka-listener:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    kafka: ERROR
    "[org.apache.jena]": ERROR
    "[org.apache.kafka]": ERROR
    "[org.apache.zookeeper]": ERROR
    "[org.chucc]": WARN
    "[org.springframework]": ERROR
    "[org.springframework.boot]": ERROR
    "[org.springframework.boot.env]": ERROR
    "[org.springframework.boot.web.servlet]": ERROR
    "[org.springframework.kafka]": ERROR
    "[org.testcontainers]": ERROR
    "[state.change.logger]": ERROR
    "[tc.testcontainers]": ERROR

