spring:
  main:
    banner-mode: off
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: vc-server-dev
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    kafka: ERROR
    "[org.apache.jena]": ERROR
    "[org.apache.kafka]": ERROR
    "[org.apache.zookeeper]": ERROR
    "[org.chucc]": WARN
    "[org.springframework]": ERROR
    "[org.springframework.boot]": ERROR
    "[org.springframework.boot.env]": ERROR
    "[org.springframework.boot.web.servlet]": ERROR
    "[org.springframework.kafka]": ERROR
    "[org.testcontainers]": ERROR
    "[state.change.logger]": ERROR
    "[tc.testcontainers]": ERROR