spring:
  application:
    name: vc-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8080
  shutdown: graceful

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.chucc: INFO
    org.springframework: INFO
    org.apache.jena: INFO

# SPARQL Version Control conformance level
# Level 1 (Basic): commits, branches, history, RDF Patch, strong ETags
# Level 2 (Advanced): three-way merge, conflicts, tags, revert, reset, cherry-pick, blame
vc:
  level: 2  # 1 or 2
  commits-enabled: true
  branches-enabled: true
  history-enabled: true
  rdf-patch-enabled: true
  merge-enabled: true
  conflict-detection-enabled: true
  tags-enabled: true
  revert-enabled: true
  reset-enabled: true
  cherry-pick-enabled: true
  blame-enabled: true
