spring:
  application:
    name: vc-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  # Security: Limit multipart file uploads
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  shutdown: graceful
  # Security: Limit request body size to prevent DoS attacks
  tomcat:
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB
  max-http-request-header-size: 16KB

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    enable:
      jvm: true
    tags:
      application: chucc-server

logging:
  level:
    kafka: ERROR
    org.apache.jena: ERROR
    org.apache.kafka: ERROR
    org.apache.zookeeper: ERROR
    org.chucc: WARN
    org.springframework: ERROR
    org.springframework.kafka: ERROR
    org.testcontainers: ERROR
    state.change.logger: ERROR
    tc.testcontainers: ERROR


# SPARQL Version Control conformance level
# Level 1 (Basic): commits, branches, history, RDF Patch, strong ETags
# Level 2 (Advanced): three-way merge, conflicts, tags, revert, reset, cherry-pick, blame
vc:
  level: 2  # 1 or 2
  commits-enabled: true
  branches-enabled: true
  history-enabled: true
  rdf-patch-enabled: true
  merge-enabled: true
  conflict-detection-enabled: true
  tags-enabled: true
  revert-enabled: true
  reset-enabled: true
  cherry-pick-enabled: true
  blame-enabled: true
  snapshots-enabled: true
  snapshot-interval: 100  # Create snapshot every N commits
  cache:
    max-size: 100  # Maximum number of cached dataset graphs
    keep-latest-per-branch: true  # Always cache latest commits
    ttl-minutes: 0  # No TTL by default (0 = disabled)

# Kafka event streaming configuration
kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topic-template: vc.{dataset}.events
  partitions: 3
  replication-factor: 1
  retention-ms: -1  # -1 for infinite retention
  compaction: false  # false for append-only (no log compaction)
