spring:
  main:
    banner-mode: off
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: vc-server-dev
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Development Kafka configuration (optimized for speed, single broker)
kafka:
  bootstrap-servers: localhost:9092

  # DEVELOPMENT: Single broker (no fault tolerance needed)
  partitions: 3
  replication-factor: 1

  # Producer: Speed over durability
  producer:
    acks: 1  # Leader only (faster)
    enable-idempotence: false  # Not needed for dev
    compression-type: none  # No compression (faster)
    retries: 3
    linger-ms: 0  # Send immediately
    batch-size: 16384  # 16KB batches

  # Consumer: Read uncommitted for lower latency
  consumer:
    isolation-level: read_uncommitted
    enable-auto-commit: true
    auto-commit-interval-ms: 1000
    max-poll-records: 500

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    kafka: ERROR
    "[org.apache.jena]": ERROR
    "[org.apache.kafka]": ERROR
    "[org.apache.zookeeper]": ERROR
    "[org.chucc]": WARN
    "[org.springframework]": ERROR
    "[org.springframework.boot]": ERROR
    "[org.springframework.boot.env]": ERROR
    "[org.springframework.boot.web.servlet]": ERROR
    "[org.springframework.kafka]": ERROR
    "[org.testcontainers]": ERROR
    "[state.change.logger]": ERROR
    "[tc.testcontainers]": ERROR