spring:
  kafka:
    consumer:
      group-id: vc-server-it
      auto-offset-reset: earliest
    producer:
      acks: all

# Disable transactional Kafka for integration tests with Testcontainers
# Testcontainers Kafka doesn't require transactions and simplifies testing
kafka:
  transactional-id-prefix: ""

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.chucc: DEBUG
    org.springframework.kafka: INFO
    org.apache.jena: INFO
