name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B clean compile

    - name: Run unit tests
      run: mvn -B test

    - name: Run integration tests
      run: mvn -B verify -Pit

    - name: Run SpotBugs
      run: mvn -B spotbugs:check

    - name: Run Checkstyle
      run: mvn -B checkstyle:check

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          target/surefire-reports/
          target/failsafe-reports/

    - name: Upload SpotBugs results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: spotbugs-results
        path: target/spotbugsXml.xml

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: target/*.jar
